### ISSUE TITLE
Scipy constants instead of burnt-it variables

### ISSUE THREAD

**Issue by matyasaradi** [gergopokol/renate-od#110]
Use [scipy constants](https://docs.scipy.org/doc/scipy/reference/constants.html) in utility/constants.py instead of burnt-it variables!

**Comment by asztalosors** [comment]
You are right. Though if one looks up the physical  constants (the definition for constants used here is slightly expanded) available within scipy: https://docs.scipy.org/doc/scipy/reference/constants.html is quite wast. There are certain constant values available in packages like (https://pypi.org/project/mendeleev/) which are not available in scipy.

The usage of a constants object or collection native to RenateOD should provide a selfconsisten collection of constants. For the stand alone uses data populated by scipy and augmented with discrepancies. For the use of RenateOD in IMAS or other integrated coding platform, constant db-s provided by said platforms should be adapted by the before mentioned object/collection.

**Comment by asztalosors** [comment]
Not surprising, the switch to different constants broke some test. The Unit tests require update.

**Comment by asztalosors** [comment]
This issue is fixed and should be considered closed for the moment.
