### ISSUE TITLE
Bug in data visualization

### ISSUE THREAD

**Issue by andorfi** [gergopokol/renate-od#113]
In development branch I got the following error when going through the default tests:

Data is NOT located in the common local directory: C:\RenateOD\utility\..\common_data\output/beamlet/beamlet_test.xml
Data is located in the user local directory: C:\RenateOD\utility\..\data\output/beamlet/beamlet_test.xml
ElementTree read from: C:\RenateOD\utility\..\data\output/beamlet/beamlet_test.xml
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-9f803cac4266>", line 1, in <module>
    t=BeamletProfiles()
  File "C:\RenateOD\visualization\profiles.py", line 12, in __init__
    self.access_path = self.param.getroot().find('body').find('beamlet_profiles').text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by asztalosors** [comment]
Ran plotting routines. All work just fine.
