### ISSUE TITLE
XML data file reader utility

### ISSUE THREAD

**Issue by gergopokol** [gergopokol/renate-od#12]
Inputs should be read from XML files. A general reader class is to be constructed in the utility module.

**Comment by SzondyB** [comment]
http://www.diveintopython3.net/xml.html

**Comment by gergopokol** [comment]
If we decide to use pandas.DataFrame as output: 
http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

**Comment by gergopokol** [comment]
This is the one we should use: lxml (standard Python package)
http://lxml.de/tutorial.html
http://infohost.nmt.edu/tcc/help/pubs/pylxml/web/index.html
