### ISSUE TITLE
Noise generator class

### ISSUE THREAD

**Issue by asztalosors** [gergopokol/renate-od#120]
As stated in issue #119 the random number generator class RandomState will be considered parent class to the Noise generator as is has already all built-in features for random number generation.

The class needs be able to generate a set of various noise types and random numbers. Signal values will not be stored within the object.
Noise types to be included: 
1. Photonic noise generator (shot noise generator)
2. Dark noise generator
3. Johnson noise generator
4. Voltage noise generator

Unittesting of Noise module required. Related issues: #125  
Parent issue: #97

**Comment by asztalosors** [comment]
@andorfi If basic physics within a class is changed. The corresponding test cases have to updated to avoid failure!!

**Comment by gergopokol** [comment]
.txt files to be cleaned up.

**Comment by asztalosors** [comment]
Class is finished and tested.
