### ISSUE TITLE
Refactoring and unit testing of utility routines

### ISSUE THREAD

**Issue by gergopokol** [gergopokol/renate-od#15]
`GetData` and `Settings` utility classes should be refactored and unit tests implemented. These are general purpose features to be used in other projects, as well, so particular care should be taken.

**Comment by gergopokol** [comment]
Might need infrastructure to read from XML config files produced by the measurement systems. Some examples added.

[APD-XML.zip](https://github.com/gergopokol/renate-od/files/1775035/APD-XML.zip)

**Comment by gergopokol** [comment]
Downloaded **data version should be logged** and made available for routines that in turn should include it in the output. Version numbers are to be stored in the XML records in the data root folder. The `dummy `property should also be stored in this file. A refresh switch is to be implemented in the data reader, which would download the most recent version of the data files requested. 

On the long run, data will be stored in an SVN repo that is to be checked out to the appropriate folders of the data user. Data downloader will have to access the SVN revision number for the selected file, and store it the local data XML.

**Comment by gergopokol** [comment]
Use of https://github.com/martinblech/xmltodict might be considered but only after solving the environment is set up in #1.

**Comment by gergopokol** [comment]
beamlet/test.xml corrected (<meta> tag had no closing --> deleted) xml reader in GetData tested.

**Comment by gergopokol** [comment]
new version of beamlet/test.xml uploaded

**Comment by gergopokol** [comment]
GetData tested for XML reading.
GetData buggy for H5 reading. --> Need debugging!

**Comment by gergopokol** [comment]
Using HDFView+Object 2.14 https://support.hdfgroup.org/products/java/release/download.html to check h5 file.

**Comment by gergopokol** [comment]
beamlet/test_profiles.h5: typos corrected, converted using convert.py.

**Comment by gergopokol** [comment]
beamlet test data files had to be updated at the public dummy directory. **Public rates data still missing**, so now there is no way to run the code on dummy data.

**Comment by gergopokol** [comment]
SCP download fails on some Windows computers due to "'pscp' is not recognized as an internal or external command, operable program or batch file." This might have to do with setting msi installer (https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) to add path to cmd path. To be tested.

**Comment by gergopokol** [comment]
**'pscp' is not recognized**:  Problem was indeed solved by properly installing putty.

**Comment by gergopokol** [comment]
One does not need access to the data user of the deep server to access the private data. It is enough to have any access to the deep server, and set the getdata_setup.xml as:

```
    <server_private_address>user@deep.reak.bme.hu:/home/data/private_html/renate-od</server_private_address>
    <private_key>full_path_of_key_file.ppk</private_key>

```

**Comment by gergopokol** [comment]
Beamlet.write_beamlet_profiles() is to be moved to utility.writedata.write_beamlet_data() with inputs of param and profiles variables and location data read from getdata_setup.xml.

This routine is then to be used to save both beamlet calculation results and data read from IMAS in wrapper_1d.

**Comment by gergopokol** [comment]
getdata.setup_rate_coeff_arrays() and getdata.get_mass() should not be in the general purpose utility package.

**Comment by gergopokol** [comment]
getdata.get_mass()  can be moved to Beamlet class, and at the initialization of Beamlet mass can be loaded and added to the param tree along with the calculated velocity.

getdata.setup_rate_coeff_arrays() can be moved back to the original location in Rates class, and when calling initialize_ode() of the Beamlet class, the Einstein coefficient(s) responsible for the observed line can be added to the params tree. Observed transition is to be added to the input params structure as optional parameter. If given, the given transition is to be used, if not, the default should be set based on the beam species.

**Comment by gergopokol** [comment]
Example of xmlTree manipulation: #12

**Comment by asztalosors** [comment]
Removed redundant code from utility package. The code is ready for unittest development and subsequent optimization. May the fun begin :)

**Comment by gergopokol** [comment]
This has been mostly done. Follow up issues: #136 #137 #110 #139 #140
