### ISSUE TITLE
MPPC noise modelling

### ISSUE THREAD

**Issue by andorfi** [gergopokol/renate-od#160]
After we've written the noise moddelling of APD, PMT and PPD, we need to write this for Multi-Pixel Photon Counters (silicon photomultiplier, SiPM). These detectors are able to measure singel photons. It is important about ITER's BES measurements.
A good source for this, is the Hamamtsu MPPC description, which is available at: https://www.hamamatsu.com/resources/pdf/ssd/mppc_kapd9005e.pdf

**Comment by asztalosors** [comment]
This issue is related to and falls under the umbrella of  #97

**Comment by asztalosors** [comment]
The MPPC Gaussian noise model is considered to be acceptable as is.
