### ISSUE TITLE
Beamlet profile outputs in "data" folder.

### ISSUE THREAD

**Issue by Balazs-Peter** [gergopokol/renate-od#178]
The WriteData.write_beamlet_profiles() function creates a "data" directory on the level of the script, and recreates the given path in this folder. In the case given, the outputs are written in the "data/output/" folder.

**Code:**
from crm_solver.beamlet import Beamlet
import os
from utility.writedata import WriteData

common_dir=os.path.dirname(__file__)+'/'
data_path=common_dir+'ROD_inputs/xml/basic_N200_a0.2_paH_baLi_10keV.xml'
output_dir='output/'

b = Beamlet(param=None, profiles=None, components=None, solver='numerical', data_path=data_path)
w = WriteData()
b.compute_linear_density_attenuation()
w.write_beamlet_profiles(b, output_dir)

**Comment by gergopokol** [comment]
Could use "user_local_data_directory" from utility/getdata_setup.xml. Will do together.

**Comment by gergopokol** [comment]
utility/writedata.py should be amended.
