### ISSUE TITLE
H - cross-section data

### ISSUE THREAD

**Issue by Balazs-Peter** [gergopokol/renate-od#188]
Creating layered dictionaries for H data:

*Dictionary for atomic input parameters.
*Dictionary for atomic cross-section functions.

Sources: ALADDIN

##### 2022.01.21 Update #####

Cross-section data should be contained by a class, that has a few public methods and properties, including but not limited to:
- get_cross_section(transition, energy)
- description
- atomic_levels
- transition_checker(transition)

**Comment by gergopokol** [comment]
Double-checked and benchmarked.
