### ISSUE TITLE
Fix h5 data reading

### ISSUE THREAD

**Issue by SzondyB** [gergopokol/renate-od#27]

**Comment by SzondyB** [comment]
Our hdf5 files has a 'fixed' format. (Fast writing/reading. Not-appendable, nor searchable.)
Data format can be changed to 'table' (Write as a PyTables Table structure which may perform worse but allow more flexible operations like searching / selecting subsets of the data.) This could be specified in writedata.WriteData() class, write_beamlet_profiles function. With data_columns=profiles.keys(), this method creates a hdf5 file with 1 table with the defined column keys.
This modification did not solve the problem, it should only be considered as a suggestion.

**Comment by SzondyB** [comment]
The h5 files are correct. The problem comes from a bad access_path given in the xml file.
When running write_beamlet_profiles, it saves a h5 and an xml file with the same name. The xml should point to the h5 file but the function overwrites the 'beamlet_profiles' path to a wrong path.

**Comment by asztalosors** [comment]
Master fix needed.

**Comment by SzondyB** [comment]
Before running 

- the test0001.xml file with <beamlet_profiles> corrected to <beamlet_source> should be in data/beamlet directory 

- data/output/beamlet/beamlet_test.xml either should not exist or should not contain <beamlet_profiles> element

**Comment by asztalosors** [comment]
Tested. Works only if output folder structure exists. The support folder structure should be created

**Comment by SzondyB** [comment]
Now the local data output directory structure is created automatilcally.

**Comment by SzondyB** [comment]
Merge to development and to adding-impurity branch tested, issue can be closed
