### ISSUE TITLE
Add GitHub Action

### ISSUE THREAD

**Issue by matyasaradi** [gergopokol/renate-od#276]
A simple CI will be set up as a GitHub action for the repository.

**Comment by matyasaradi** [comment]
For further explanation, explore:
https://docs.github.com/en/actions/learn-github-actions/using-starter-workflows

**Comment by matyasaradi** [comment]
Here is a list for supported Python versions:
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Comment by matyasaradi** [comment]
If you would like to see the past CIs, press on the Actions button:
https://github.com/gergopokol/renate-od/actions

**Comment by gergopokol** [comment]
Completed, merged to development
