### ISSUE TITLE
Implement rate loader routine

### ISSUE THREAD

**Issue by gergopokol** [gergopokol/renate-od#3]
Rates (and any other data) should not be stored in the source code repository, rather it should be stored locally, and downloaded from a website if needed.

**Comment by plasmatyi** [comment]
Dear Gergo Pokol,

The email sent to github@maradi.tk with subject
"Re: [gergopokol/renate-od] Implement rate loader routine (#3)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to github@maradi.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by asztalosors** [comment]
Correction made to routine regarding relative paths. The correction needs to be test in different environments.

**Comment by plasmatyi** [comment]
Dear asztalosors,

The email sent to github@maradi.tk with subject
"Re: [gergopokol/renate-od] Implement rate loader routine (#3)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to github@maradi.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by gergopokol** [comment]
General purpose utility development continued in #13 . Specialized rate loader continued here.

**Comment by gergopokol** [comment]
It could be considered to move this routine into the general purpose GetData class. Testing and review is necessary.

**Comment by gergopokol** [comment]
All functions moved to GetData in #15.
