### ISSUE TITLE
Clean coding 1st

### ISSUE THREAD

**Issue by MindlerGergely** [gergopokol/renate-od#32]
This is the next step in clean coding after #21 that was its introduce issue. Our purposes now are more formatting, clarify ode processes and build a real module.

Relevant branch: clean-coding-1st

**Comment by asztalosors** [comment]
Beam evolution calculation successful in branch. Branch is ready to be merged back into development

![Beam-evolution_in_CC_first](https://user-images.githubusercontent.com/26080385/55316699-40656280-546f-11e9-9742-dcfeedd537ae.png)

**Comment by gergopokol** [comment]
Associated pull request merged, branch to be deleted, the issue can be closed.
