### ISSUE TITLE
What is the recommended installation pattern for Renata-OD?

### ISSUE THREAD

**Issue by mattngc** [gergopokol/renate-od#33]
Hi,

Just preparing to play with your module after some discussions with @asztalosors at JET this week. I was wondering what the recommended installation pattern is? I didn't see a setup.py in the root folder so I'm guessing you aren't using "python setup.py install" or something similar? Maybe you are putting the root project folder on your python path manually? 

Regards, Matt

**Comment by asztalosors** [comment]
Dear Matt, 
RENATE-OD has no install protocol so far.  The wikipage "How to run" contains instructions on how to operate the code. A tested and operational version will be made available to you next week.

**Comment by mattngc** [comment]
Thanks Ors, no worries. Let me know when you have the version ready for testing.

**Comment by mattngc** [comment]
Resolved with the getting started guide that has been added to the wiki.
