### ISSUE TITLE
Directory reference with respect to module

### ISSUE THREAD

**Issue by gergopokol** [gergopokol/renate-od#45]
CHERAB integration requested for the use of the file (module) location as the basis for the relative directory reference as opposed to the reference relative to the current directory. Accordingly, pull request #44 have been merged into the dedicated [gergopokol:relative_reference](https://github.com/gergopokol/renate-od/tree/relative_reference) branch.

This issue is to extend this style of reference throughout the code.

**Comment by gergopokol** [comment]
This works. Also with CHERAB. Can be closed.

**Comment by asztalosors** [comment]
This issue is closed. Migrating the issue back to 1.1.0.
