### ISSUE TITLE
Setup script

### ISSUE THREAD

**Issue by gergopokol** [gergopokol/renate-od#46]
Matt has proposed to add a Python setup script in pull request #39. This has been merged to branch https://github.com/gergopokol/renate-od/tree/add_setup for further exploration.

**Comment by gergopokol** [comment]
Some useful info:
https://github.com/pypa/sampleproject/blob/master/setup.py 
https://packaging.python.org/guides/distributing-packages-using-setuptools/#setup-py

**Comment by mattngc** [comment]
You can also have a look at the Raysect and CHERAB ones as examples:
https://github.com/raysect/source/blob/master/setup.py
https://github.com/cherab/core/blob/master/setup.py

Ours has extra stuff in it for Cython compilation but gives you an idea of what is possible.

**Comment by gergopokol** [comment]
Branch add_setup deleted. This is to be continued in branch https://github.com/gergopokol/renate-od/tree/cherab_integration_pull. Having proper setup.py is actually required by CHERAB, so it is to be fixed.

**Comment by gergopokol** [comment]
Tested on ITER cluster.

setup() uses Cython, so adaption to standalone RENATE-OD might decrease portability, so this is postponed.
