### ISSUE TITLE
CHERAB integration

### ISSUE THREAD

**Issue by asztalosors** [gergopokol/renate-od#56]
The Issue centers around modifications and optimizations that improve RENATE-OD operations within the CHERAB framework.
Issues to be done:
1. Remove atomic database initialization from the beamlet object. The atomic (mostly the interpolation routines) db will be passed as a variable to the beamlet object.
2. More enhancements will be added as project matures

**Comment by gergopokol** [comment]
CHERAB integration done. It runs like this: https://github.com/gergopokol/renate-od/wiki/User's-Guide

Related branch is to be merged and closed.
