### ISSUE TITLE
Development of BES - IDS interface

### ISSUE THREAD

**Issue by asztalosors** [gergopokol/renate-od#6]
Development BES - CPO and infrastructure for EU-IM integration processes.

**Comment by asztalosors** [comment]
Added preliminary documentation for BES - CPO

**Comment by asztalosors** [comment]
Added most part of BES CPO

**Comment by gergopokol** [comment]
CPO design will not be completed, as no new data structure release is expected. Instead the data structure is to be produced in IDS of IMAS.

**Comment by gergopokol** [comment]
Details at https://git.iter.org/projects/IMAS/repos/data-dictionary/pull-requests/79/overview 

## Issue closed.
