### ISSUE TITLE
Visualization of population evolution along beam

### ISSUE THREAD

**Issue by gergopokol** [gergopokol/renate-od#7]
Output of the 1D beam simulation is to be visualized from saved hdf5 output. All ipnut data and population evolution is to be plotted.

**Comment by SzondyB** [comment]
To do:
- self.profiles read to __init__
- setting axis properties to separate functions
- plotting functions: create axis, call function

**Comment by gergopokol** [comment]
access_path should point to the xml file specifying the run parameters. The path to the corresponding h5 file is to be read from it. Similarly to the Beamlet class.

**Comment by gergopokol** [comment]
benchmark_to_renate() is to be changed to benchmark(reference_data_path) routine that can compare any arbitrary profile result files. 

Run parameters are also to be plotted and compared. These should also be plotted on the plot_all_profiles() plots.

**Comment by gergopokol** [comment]
xml files should be taken as input, and information there to be visualized on the plot.

**Comment by asztalosors** [comment]
The issue has long been fixed.
