### ISSUE TITLE
1D observation module

### ISSUE THREAD

**Issue by asztalosors** [gergopokol/renate-od#8]
Create an 1D observation module.
- emission along beam calculated by multiplying with beam current and spontaneous emission fractions.
- photon current integration along beamlet for designated sections along the beam.

**Comment by gergopokol** [comment]
Beamlet current is to be added as property of the Beamlet class, and read from there.

**Comment by gergopokol** [comment]
Renames necessary:
input_obj --> beamlet
input_param  --> beamlet_param
input_profiles --> beamlet_profiles

**Comment by gergopokol** [comment]
calculate_light_profile() to be refactored using vector operations and short internal variable names

**Comment by gergopokol** [comment]
self.input_param = input_obj.param
        self.input_profiles = input_obj.profiles
can be removed, and use references like beamlet.param instead.

**Comment by asztalosors** [comment]
Functionality of this module will be taken over by CHERAB. Do we need this issue alive?

**Comment by SzondyB** [comment]
![interp_onoff](https://user-images.githubusercontent.com/25754664/64196246-b9843e00-ce83-11e9-9755-b9a723886e63.png)
Observed photon emission profile: with - blue - and without interpolation - orange.
