### ISSUE TITLE
Adding Noise to Synthetic signals

### ISSUE THREAD

**Issue by asztalosors** [gergopokol/renate-od#97]
A module is needed to add noise to modeled BES signals. The basic description:

1. Read and write synthetic BES signals
2. Add noise.
-------------------------------------------
Noise model should be based on paper of: Dunai: https://doi.org/10.1063/1.3488458 for APD detectors.
1. A Poisson noise should be added based on photon count within a sampling period.
2. Based on the mean photon value of the signal, and a SBR a background photon noise will be added to the signal.
3. An amplifier noise will be added that scales with the photon current strength. See equation (1).
4. The Johnson noise will be added following a Gaussian distribution.

**Comment by asztalosors** [comment]
Related issue for data reading #112

**Comment by andorfi** [comment]
[first suggestions.pdf](https://github.com/gergopokol/renate-od/files/5083672/first.suggestions.pdf)

In this pdf you can read our first suggestions to the work.

**Comment by asztalosors** [comment]
After discussions with @gergopokol the following class structure was agreed upon.
<img width="592" alt="Noise Class Design" src="https://user-images.githubusercontent.com/26080385/92220994-12265680-ee9d-11ea-911e-733b7b12c560.PNG">

**Comment by asztalosors** [comment]
The class design principles should correlated to: http://butunclebob.com/ArticleS.UncleBob.PrinciplesOfOod

**Comment by asztalosors** [comment]
Added MPPC detector modelling #160

**Comment by gergopokol** [comment]
Reviewed.
